name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

## thanks to https://github.com/mff-cuni-cz/cuni-thesis-validator
jobs:
  build:
    name: Build PDF and upload as an artifact
    runs-on: ubuntu-latest
    container: { image: 'aergus/latex' }
    steps:
      - name: Instal git-lfs
        run: apt-get update && apt-get install -y git-lfs
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Build the PDF
        run: latexmk thesis
      - name: Upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: Thesis
          path: thesis.pdf
  verify:
    name: Verify PDF/A
    runs-on: ubuntu-latest
    needs: build
    container: { image: ghcr.io/jdujava/cuni-thesis-validator }
    steps:
      - name: Get the PDF file from the artifact
        uses: actions/download-artifact@v4
      - name: Verify the PDF file with VeraPDF
        run: verify Thesis/*.pdf | tee /dev/stderr | grep -qE 'nonCompliant="0" failedJobs="0"'
